### ISSUE TITLE
customElements is not defined

### ISSUE THREAD

**Issue by sibelius** [RobinHerbots/Inputmask#2298]
After upgrading jest, I've got this error below,  customElements is not defined

is there a way to polyfill this? or just avoiding breaking?

```jsx
ReferenceError: customElements is not defined
    at Object.modules (/home/circleci/app/node_modules/inputmask/dist/inputmask.js:2701:13)
    at __webpack_require__ (/home/circleci/app/node_modules/inputmask/dist/inputmask.js:2743:34)
    at Object.modules (/home/circleci/app/node_modules/inputmask/dist/inputmask.js:641:81)
    at __webpack_require__ (/home/circleci/app/node_modules/inputmask/dist/inputmask.js:2743:34)
    at /home/circleci/app/node_modules/inputmask/dist/inputmask.js:2735:36
    at webpackUniversalModuleDefinition (/home/circleci/app/node_modules/inputmask/dist/inputmask.js:9:83)
    at Object.<anonymous> (/home/circleci/app/node_modules/inputmask/dist/inputmask.js:13:2)
    at Runtime._execModule (/home/circleci/app/node_modules/jest-runtime/build/index.js:1056:24)
    at Runtime._loadModule (/home/circleci/app/node_modules/jest-runtime/build/index.js:684:12)
    at Runtime.requireModule (/home/circleci/app/node_modules/jest-runtime/build/index.js:542:10)
    at Runtime.requireModuleOrMock (/home/circleci/app/node_modules/jest-runtime/build/index.js:705:21)
    at Object.<anonymous> (/home/circleci/app/node_modules/inputmask/index.js:1:45)
    at Runtime._execModule (/home/circleci/app/node_modules/jest-runtime/build/index.js:1056:24)
    at Runtime._loadModule (/home/circleci/app/node_modules/jest-runtime/build/index.js:684:12)
    at Runtime.requireModule (/home/circleci/app/node_modules/jest-runtime/build/index.js:542:10)
    at Runtime.requireModuleOrMock (/home/circleci/app/node_modules/jest-runtime/build/index.js:705:21)
```

**Comment by RobinHerbots** [comment]
@sibelius, 

To chich version did you upgrade?

**Comment by sibelius** [comment]
![image](https://user-images.githubusercontent.com/2005841/78357268-845ddc80-7587-11ea-9e5b-174aebe950d2.png)

25.1.0 -> 25.2.6

I'm getting this error in production as well, maybe some older browsers

**Comment by RobinHerbots** [comment]
@sibelius , 

I mean which version of inputmask.

I will push a new version to npm.

**Comment by sibelius** [comment]
inputmask@5.0.3

**Comment by RobinHerbots** [comment]
ach you will need the latest beta to fix this

**Comment by sibelius** [comment]
5.0.4?

I'm checking master code, this line:

https://github.com/RobinHerbots/Inputmask/blob/2b30e91028110e08ed0f6da6540e66804cd1af8b/lib/inputmaskElement.js#L8

does this check is enough for custom elements?

**Comment by RobinHerbots** [comment]
yes, propbaly

**Comment by RobinHerbots** [comment]
maybe also add the customElements check if that is needed (can you give feedback)
```
 if (document && document.head && document.head.attachShadow && customElements && customElements.get("input-mask") === undefined) { 
```

**Comment by sibelius** [comment]
any timeline to release the beta version?

**Comment by RobinHerbots** [comment]
To a stable release or a new beta in npm with the changes?

I can push a new beta to npm now.

**Comment by sibelius** [comment]
for a stable one

**Comment by RobinHerbots** [comment]
Not really an idea.  Asap :-)

**Comment by RobinHerbots** [comment]
Use version
inputmask@5.0.4-beta.33

Version 5.0.4 only contains bugfixes on top of 5.0.3

**Comment by sibelius** [comment]
anything missing? more automated tests?

**Comment by sibelius** [comment]
not failing anymore on jest

gonna check in production

thanks

**Comment by onoranzefunebricloud** [comment]
It's still failing for me @sibelius  🤔 

`"inputmask": "^5.0.4-beta.33",`

![Screenshot 2020-04-22 at 06 29 26](https://user-images.githubusercontent.com/39502804/79944112-a6e66580-8462-11ea-9249-4d2b1f1d2f80.png)

**Comment by RobinHerbots** [comment]
@onoranzefunebricloud,

I added an extra check for customelements. Can you have a try with beta 36
