### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'charAt')     at m.onBeforeMask

### ISSUE THREAD

**Issue by firer777** [RobinHerbots/Inputmask#2752]
- Error when null value from database use inputmask
- Inputmask lasted version

**Comment by RobinHerbots** [comment]
@sinhnv1991 ,

Can you provide some more information.  Which mask are you using? Which options etc.

**Comment by ozonerik** [comment]
i'm same problem when using livewire 2+inputmask latest version: 

`<input wire:ignore data-inputmask="'autoUnmask': true, 'suffix': ' m2','alias': 'decimal', 'radixPoint':',', 'groupSeparator': '.', 'autoGroup': true, 'digits': 2, 'digitsOptional': false, 'rightAlign': false "  id="luas" type="text" wire:model="luas" class="form-control @if($errors->has('luas')) is-invalid @endif" >
`

`<input wire:ignore data-inputmask="'autoUnmask': true, 'suffix': ' bata','alias': 'decimal', 'radixPoint':',', 'groupSeparator': '.', 'autoGroup': true, 'digits': 2, 'digitsOptional': false, 'rightAlign': false "  id="luas" type="text" wire:model="bata" class="form-control @if($errors->has('luas')) is-invalid @endif" >
`

when I write in the input box I get the following error
`
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'charAt')
    at y.onBeforeMask (inputmask.js:1784:47)
    at c (inputmask.js:1963:111)
    at HTMLInputElement.c (inputmask.js:2834:90)
    at Object.setInputValue (dom.js:179:16)
    at Object.setInputValueFromModel (dom.js:150:14)
    at index.js:367:17
    at index.js:525:17
    at walk (walk.js:5:9)
    at walk (walk.js:10:9)
    at walk (walk.js:10:9)
`

**Comment by ozonerik** [comment]
@RobinHerbots i same error when i used livewire:
but if not used alias error is gone but not mask
![image](https://github.com/RobinHerbots/Inputmask/assets/49719997/13af12a6-df5f-47b6-aff3-e348904ec77f)

if i used 'alias':'decimal' i got error again
![image](https://github.com/RobinHerbots/Inputmask/assets/49719997/e68bd050-c8d0-497e-95a3-a058f7534f9d)

**Comment by RobinHerbots** [comment]
Fixed on current releases: the numeric `onBeforeMask` now guards the incoming value (`initialValue = initialValue ?? ""` in `lib/extensions/numeric.js`), so a null/undefined value no longer throws a `charAt` TypeError.

Closing as resolved — if you can still reproduce with the latest version, please reopen with the exact mask, options, and the value being set.
